# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.6.0]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Set up SSH agent
      run: eval "$(ssh-agent -s)"
           ssh-add "${{ secrets.MATH_SSH_KEY }}"
    - name: Build website
      run: yarn build:production
    - name: Deploy website
      run: ./deploy.sh
